### ISSUE TITLE
Use by `image` crate

### ISSUE THREAD

**Issue by fintelia** [jansol/texpresso#1]
There's some talk in https://github.com/image-rs/image/pull/1495 of using this crate to implement DDS encoding/decoding for `image`. The two main things we'd be looking for are support for BC4/BC5 (most of the code already exists for BC3 handling so it would just be a matter of exposing it), and to get a new version published on crates.io. Would you be open to this?

**Comment by Waelwindows** [comment]
What's the status on this? texpresso seems to support BC4/BC5 now
